### ISSUE TITLE
tc-admin apply throws an error

### ISSUE THREAD

**Issue by helfi92** [mozilla/community-tc-config#281]
`tc-admin apply --with-secrets --ids-only --grep proj-taskcluster` throws:

```
Traceback (most recent call last):
  File "/Users/hassanali/Documents/Mozilla/projects/community-tc-config/sandbox/bin/tc-admin", line 11, in <module>
    load_entry_point('tc-admin==2.2.0', 'console_scripts', 'tc-admin')()
  File "/Users/hassanali/Documents/Mozilla/projects/community-tc-config/sandbox/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/hassanali/Documents/Mozilla/projects/community-tc-config/sandbox/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2853, in load_entry_point
    return ep.load()
  File "/Users/hassanali/Documents/Mozilla/projects/community-tc-config/sandbox/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2453, in load
    return self.resolve()
  File "/Users/hassanali/Documents/Mozilla/projects/community-tc-config/sandbox/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2459, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/hassanali/Documents/Mozilla/projects/community-tc-config/sandbox/lib/python3.7/site-packages/tc_admin-2.2.0-py3.7.egg/tcadmin/boot.py", line 10, in <module>
    from .main import main
  File "/Users/hassanali/Documents/Mozilla/projects/community-tc-config/sandbox/lib/python3.7/site-packages/tc_admin-2.2.0-py3.7.egg/tcadmin/main.py", line 13, in <module>
    from .util.sessions import with_aiohttp_session
  File "/Users/hassanali/Documents/Mozilla/projects/community-tc-config/sandbox/lib/python3.7/site-packages/tc_admin-2.2.0-py3.7.egg/tcadmin/util/sessions.py", line 7, in <module>
    import aiohttp
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/hassanali/Documents/Mozilla/projects/community-tc-config/sandbox/lib/python3.7/site-packages/aiohttp-2.3.10-py3.7.egg/aiohttp/__init__.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/hassanali/Documents/Mozilla/projects/community-tc-config/sandbox/lib/python3.7/site-packages/aiohttp-2.3.10-py3.7.egg/aiohttp/client.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/hassanali/Documents/Mozilla/projects/community-tc-config/sandbox/lib/python3.7/site-packages/aiohttp-2.3.10-py3.7.egg/aiohttp/connector.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/hassanali/Documents/Mozilla/projects/community-tc-config/sandbox/lib/python3.7/site-packages/aiohttp-2.3.10-py3.7.egg/aiohttp/helpers.py", line 742, in <module>
TypeError: function() argument 1 must be code, not str
```

**Comment by djmitche** [comment]
From some experimentation, this seems to be due to some dependency change, but not aiohttp.  Python version doesn't seem to matter (3.6 or 3.7, at least).  This pip-freeze works:
```
aiohttp==2.3.10
appdirs==1.4.3
async-timeout==3.0.1
atomicwrites==1.3.0
attrs==19.3.0
autopep8==1.4.4
black==19.10b0
blessings==1.7
certifi==2019.9.11
chardet==3.0.4
Click==7.0
idna==2.8
idna-ssl==1.1.0
importlib-metadata==0.23
iso8601==0.1.12
json-e==3.0.0
memoized==0.3
mohawk==1.0.0
more-itertools==7.2.0
multidict==4.5.2
packaging==19.2
pathspec==0.6.0
patiencediff==0.1.0
pluggy==0.13.0
py==1.8.0
pycodestyle==2.5.0
pyparsing==2.4.2
pytest==5.2.1
PyYAML==4.2b4
regex==2019.11.1
requests==2.22.0
six==1.12.0
slugid==2.0.0
sortedcontainers==2.1.0
taskcluster==28.0.0
taskcluster-urls==12.1.0
tc-admin==2.5.0
toml==0.10.0
typed-ast==1.4.0
urllib3==1.25.6
wcwidth==0.1.7
yamllint==1.18.0
yarl==1.3.0
zipp==0.6.0
```
while this one does not:
```
aiohttp==2.3.10
async-timeout==4.0.0a2
attrs==19.3.0
blessings==1.7
certifi==2020.4.5.1
chardet==3.0.4
click==7.1.2
community-tc-config==1.0.0
idna==2.9
idna-ssl==1.1.0
importlib-metadata==1.6.0
json-e==3.0.2
memoized==0.3
mohawk==1.1.0
more-itertools==8.3.0
multidict==4.7.6
packaging==20.4
pluggy==0.13.1
py==1.8.1
pyparsing==3.0.0a1
pytest==5.4.2
PyYAML==4.2b4
requests==2.23.0
six==1.15.0
slugid==2.0.0
sortedcontainers==2.1.0
taskcluster==21.3.0
taskcluster-urls==12.1.0
tc-admin==2.2.0
typing-extensions==3.7.4.2
urllib3==1.25.9
wcwidth==0.1.9
yarl==1.4.2
zipp==3.1.0
```

**Comment by djmitche** [comment]
```
async-timeout==4.0.0a2
```
appears to be the issue.

https://github.com/taskcluster/tc-admin/pull/77 should fix it.

**Comment by djmitche** [comment]
https://github.com/taskcluster/tc-admin/releases/tag/v2.5.1
