### ISSUE TITLE
role hook-id:project-fuzzing/fuzzing-tc-config-community-update contains cycle

### ISSUE THREAD

**Issue by petemoore** [mozilla/community-tc-config#447]
tc-admin update failure:

```
taskcluster.exceptions.TaskclusterRestFailure: Roles may not contain dependency cycles, found: 'assume:hook-id:project-fuzzing/fuzzing-tc-config-community-update' -> 'assume:hook-id:project-fuzzing/fuzzing-tc-config-community-update'
```

**Comment by petemoore** [comment]
@jschwartzentruber OK for us to delete this line?

https://github.com/mozilla/community-tc-config/blob/ae1388380db903b439ed1b17962dd2fa1d85f14f/config/projects/fuzzing.yml#L538

**Comment by petemoore** [comment]
@jschwartzentruber It looks like #448 didn't entirely resolve the issue unfortunately.

```
Fetching secrets with passwordstore
Secrets fetched
Creating Role=hook-id:project-fuzzing/fuzzing-tc-config-community-update
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/tcadmin/update.py", line 114, in update_resource
    await getattr(self, "{}_{}".format(verb, resource.kind.lower()))(resource)
  File "/usr/local/lib/python3.9/site-packages/tcadmin/update.py", line 44, in create_role
    await self.auth.createRole(role.roleId, role.to_api())
  File "/usr/local/lib/python3.9/site-packages/taskcluster/generated/aio/auth.py", line 242, in createRole
    return await self._makeApiCall(self.funcinfo["createRole"], *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/taskcluster/aio/asyncclient.py", line 93, in _makeApiCall
    response = await self._makeHttpRequest(entry['method'], _route, payload)
  File "/usr/local/lib/python3.9/site-packages/taskcluster/aio/asyncclient.py", line 209, in _makeHttpRequest
    return await retry.retry(self.options['maxRetries'], tryRequest)
  File "/usr/local/lib/python3.9/site-packages/taskcluster/aio/retry.py", line 32, in retry
    res = await tryFn(retryFor)
  File "/usr/local/lib/python3.9/site-packages/taskcluster/aio/asyncclient.py", line 195, in tryRequest
    raise exceptions.TaskclusterRestFailure(
taskcluster.exceptions.TaskclusterRestFailure: Roles may not contain dependency cycles, found: 'assume:hook-id:project-fuzzing/fuzzing-tc-config-community-update' -> 'assume:hook-id:project-fuzzing/fuzzing-tc-config-community-update'

---

* method:     createRole
* errorCode:  InputError
* statusCode: 400
* time:       2021-11-10T17:48:47.151Z

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/tc-admin", line 8, in <module>
    sys.exit(boot())
  File "/usr/local/lib/python3.9/site-packages/tcadmin/boot.py", line 65, in boot
    main(appconfig)
  File "/usr/local/lib/python3.9/site-packages/tcadmin/main.py", line 122, in main
    cmd()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/tcadmin/main.py", line 29, in wrap
    return loop.run_until_complete(fn(*args, **kwargs))
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/tcadmin/util/sessions.py", line 26, in wrap
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/tcadmin/main.py", line 120, in applyCommand
    await apply.apply_changes(expected, actual)
  File "/usr/local/lib/python3.9/site-packages/tcadmin/apply.py", line 35, in apply_changes
    await updater.update(generated, current)
  File "/usr/local/lib/python3.9/site-packages/tcadmin/update.py", line 142, in update
    await self.update_resource(ACTION_CREATE, g)
  File "/usr/local/lib/python3.9/site-packages/tcadmin/update.py", line 116, in update_resource
    raise RuntimeError("Error While {}".format(strip_ansi(msg))) from e
RuntimeError: Error While Creating Role=hook-id:project-fuzzing/fuzzing-tc-config-community-update
```
